<?php
/**
 * @package     Dadolun_SibOrderSync
 * @copyright   Copyright (c) 2023 Dadolun (https://www.dadolun.com)
 * @license    This code is licensed under MIT license (see LICENSE for details)
 */
use Dadolun\SibOrderSync\ViewModel\TrackingCartData;

/**
 * @var TrackingCartData $trackingData
 */
$trackingData = $block->getData('trackingData');
$isCartTrackingEnabled = $trackingData->isCartTrackingEnabled();
?>
<?php if ($isCartTrackingEnabled): ?>
<script type="text/x-magento-init">
{
    "*": {
        "Dadolun_SibOrderSync/js/tracking/quote": {}
    }
}
</script>
<?php endif; ?>
